--- !ditz.rubyforge.org,2008-03-06/project 
name: HeadspringFizzBuzz
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: HeadspringFizzBuzz
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: Interview2
  status: :released
  release_time: 2011-11-22 09:41:25.763761 Z
  log_events: 
  - - 2011-11-22 02:05:13.278307 Z
    - Charles Suehs <skelter@skelter.net>
    - created
    - Things I'd better have ready for tomorrow
  - - 2011-11-22 09:41:25.763772 Z
    - Charles Suehs <skelter@skelter.net>
    - released
    - I wonder if I made it more complicated than it was supposed to be.
- !ditz.rubyforge.org,2008-03-06/release 
  name: PostReview
  status: :unreleased
  release_time: 
  log_events: 
  - - 2011-11-23 00:38:17.233757 Z
    - Charles Suehs <skelter@skelter.net>
    - created
    - Things to be done after that first deadline.
